config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :searches
  post 'hola', to: 'creador_api#hola'
  get 'adios', to: 'creador_api#adios'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/creador_api_controller.rb
class CreadorApiController < ActionController::API
    require 'scrapper.rb'
    queControlador('API')
    def hola
        @search = Search.create(name: params[:name])
        #render json: @search
        #redirect_to root_path
       

        # @data = clean(params[:name])
        
        # @info = scraping(@data[:title])

        # @final_data = hash_creator(@data[:keys], @info)
        # @final_data = @final_data.sort_by {|hash| - hash[:percentage]}
        # quant = @final_data.length
        # puts "Se encontaron #{quant} en total."
        #@prettyjson = {name: @data[:title].capitalize(), ans: @final_data, searchkeys: @data[:keys]}
        @prettyjson =  calling(params[:name])
        render json: @prettyjson
    end

    def adios
        render html: helpers.tag.strong("TESTEANDO LA API")
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'scrapper.rb'

  def index
    ::Saludos::Saludando.saludo('Probando codigo externo')
    @search = Search.new
    @searches = Search.all
    if params[:name] != nil
      Search.create(name: params[:name])
    end 
    #saludo(Search.last.name)
    queControlador('home')
  end
end

app/controllers/scrapper.rb
require 'nokogiri'
require 'open-uri'
require 'pry'


def separate(data)
  letters = ('a'..'z').to_a
  numbers = ('0'..'9').to_a
  elements = letters.concat(numbers)
  ans = []
  keys = []
  data.each_char do |char|
    if elements.include?(char.downcase)
      ans << char.downcase
    else
      if ans.length > 1
        keys << ans.join('')
      end
      ans = []
    end
  end
  return keys
end

def clean(movie)
	h = {}
    puts "Limpiando datos..."
    rgxTv = /([Ss]\d{2}[[Ee]\d{2}]*)/
    rgxMovie = /((\d{4})[^p])/
    puts movie
    if (rgxTv =~ movie) == nil
    	puts 'Película de nombre: '
    	name_i = rgxMovie =~ movie

    	name_i += 4

    	code = movie.scan(rgxMovie)[0]
    	code = code[1]
    else
    	puts 'Serie de nombre: '
    	name_i = rgxTv =~ movie

    	name_i += 6

   		code = movie.scan(rgxTv)[0]
   		code = code[0]
    end

    title = movie[0...name_i]
    body = movie[name_i..-1]

    keys =separate(body)
    title = separate(title).join(' ') +' '+ code
    puts title
    h = {title: title, keys: keys}
    return h
end	

def scraping(data)
	puts 'Scrapeando información...'
	data = data.split(' ').join('%20')
	h = {}
	p "http://www.subdivx.com/index.php?q=#{data}&accion=5&masdesc=&subtitulos=1&realiza_b=1"
	html = open("http://www.subdivx.com/index.php?q=#{data}&accion=5&masdesc=&subtitulos=1&realiza_b=1")
	#crea un objeto tipo Nokogiri HTML con la info de la web.
	doc = Nokogiri::HTML(html)
	links = {}
	description = []
	downloads = []
	links = []

	doc.search('#buscador_detalle_sub').map.with_index do |ele, i|
	    description << ele.content
	end

	doc.search('#buscador_detalle_sub_datos').map do |ele|
		downloads << ele.content.scan(/: (\d*,?\d+)/)[0][0].tr(',','').to_i
	end

	doc.search('.titulo_menu_izq').map.with_index do |ele, i|
    	links << ele['href']
   	end

	h = {description: description, downloads: downloads, links: links}
	#ele.at_css("b").content
end

def search(str, keys)
	arr = []
	keys.each do |ele|
		if str.scan(ele).length > 0
			arr << ele
		end
	end
	return arr
end


def hash_creator(keys, data)
	results = []
	sub_list = data[:description]
	sub_list.each.with_index do |ele,i|
		h = {
		 i: i,
		desc:  (ele),
		array: [],
		percentage: 0,
		downloads: 0,
		links: []
	}
		h[:array] = search(ele, keys)
		h[:percentage] = ((h[:array].length) *100)/keys.length
		h[:downloads] = data[:downloads][i]
		h[:links] = data[:links][i]
		results << h
	end
	return results
end



def calling(str)
	puts '////////////////////////////////////////////////////////////////////////////////////////////////' 

	string = str

    data = clean(string)
    
	info = scraping(data[:title])

	p data[:keys]
    puts
    
	final_data = hash_creator(data[:keys], info)
	quant = final_data.length
	puts "Se encontaron #{quant} en total."
	order = final_data.sort_by {|hash| [-hash[:percentage], -hash[:downloads]]}
	final_hash = {name: data[:title].capitalize() , ans: order, searchkeys: data[:keys] }
end

def queControlador(str)
    puts "Estoy en el controlador #{str}."
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creador_api_helper.rb
module CreadorApiHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/home/index.html.erb
<h1>Arrastra o Selecciona el archivo para buscar subtítulos</h1>
<h3 id="keys"></h3>


<%#= render './searches/form', search: @search %>
<br>
<%#= link_to 'Back', root_path %>
<div id="answer">
    <form>
    <div class="form-group">
        <input type="file" id="name" class="form-control-file">
    </div>
    </form>
    <div class="dropzone" id="dropzone">Arrastra el archivo aquí</div>
</div>
<br>
<br>
<h1> Últimas búsquedas ... <%#= Search.last.name %> </h1>
<ul id="lista">
    <% @searches.reverse_each.with_index do |ele,i| %>
        <% if i < 5 %>
        <li><%= ele.name %></li>
        <% end %>
    <%end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Seleccionar película" %>
    <%= form.file_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Buscar Subtítulos" %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.name %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @search.name %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', root_path %>